version: "2.3"

services:
  web:
    build:
      context: .
      target: bpsky-be-image
    container_name: bpe-be-ctn-dev
    image: bpsky-be-image
    volumes:
      - ./:/python/src/bpe
    ports:
      - "8000:8000"
    working_dir: /python/src/bpe
    command: sh -c "pip install -r ./requirements.txt && python run.py"
    depends_on:
      - db
    restart: unless-stopped
    tty: true

  db:
    container_name: bpsky-db-ctn-dev
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql

volumes:
  postgres:
    name: postgres-dev
    driver: local
