init_questions = [
    {
        "id": 1,
        "content": "Do you use any products or services provided by this process?",
        "question_type": "branching",
        "section_id": 0,
        "order_in_section": 0,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 2,
        "content": "What is your role in this process?",
        "question_type": "multiple_choice",
        "section_id": 1,
        "order_in_section": 0,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 3,
        "content": 'To what extent do you agree with this statement: "It is easy to handle exceptions in your process".',
        "question_type": "ces",
        "section_id": 1,
        "order_in_section": 1,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 4,
        "content": 'To what extent do you agree with this statement: "It is easy to execute your process."',
        "question_type": "ces",
        "section_id": 1,
        "order_in_section": 2,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 5,
        "content": "How frequently do exceptions happen in practice?",
        "question_type": "ces-in",
        "section_id": 1,
        "order_in_section": 3,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 6,
        "content": "Which handled exceptions do you think the way to handle them needs optimizing? Can you suggest some solutions to those?",
        "question_type": "ces-in",
        "section_id": 1,
        "order_in_section": 4,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 7,
        "content": "Can you suggest any exceptions that need handling and the way to handle them?",
        "question_type": "ces-in",
        "section_id": 1,
        "order_in_section": 5,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 8,
        "content": "How satisfied are you with the way exceptions are handled in your process?",
        "question_type": "csat",
        "section_id": 1,
        "order_in_section": 6,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 9,
        "content": "How satisfied are you with the amount of time you have to spend on this process?",
        "question_type": "csat",
        "section_id": 1,
        "order_in_section": 7,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 10,
        "content": "A flexible process means it has variations for different conditions. How satisfied are you with those variations of the process?",
        "question_type": "csat",
        "section_id": 1,
        "order_in_section": 8,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 11,
        "content": "How satisfied are you with the cost of products or services of this process?",
        "question_type": "csat",
        "section_id": 2,
        "order_in_section": 0,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 12,
        "content": "How satisfied are you with the products or services provided by this process?",
        "question_type": "csat",
        "section_id": 2,
        "order_in_section": 1,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 13,
        "content": "How satisfied are you with the total time you have to spend on waiting for the output of this process?",
        "question_type": "csat",
        "section_id": 2,
        "order_in_section": 2,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 14,
        "content": "Do you encounter any problems while using products or services provided by this process?",
        "question_type": "csat-in",
        "section_id": 2,
        "order_in_section": 3,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
    {
        "id": 15,
        "content": "How likely is it that you would recommend this process to others?",
        "question_type": "nps",
        "section_id": 3,
        "order_in_section": 0,
        "weight": 1,
        "is_required": True,
        "is_deleted": False,
        "origin": "system",
        "domain": "general",
        "contributor_id": None,
        "usage_count": 0,
    },
]

init_questions_options = [
    {
        "content": "Yes",
        "order_in_question": 0,
        "question_id": 1,
        "is_deleted": False,
    },
    {
        "content": "No",
        "order_in_question": 1,
        "question_id": 1,
        "is_deleted": False,
    },
    {
        "content": "lane 1",
        "order_in_question": 0,
        "question_id": 2,
        "is_deleted": False,
    },
    {
        "content": "lane 2",
        "order_in_question": 1,
        "question_id": 2,
        "is_deleted": False,
    },
    {
        "content": "lane 3",
        "order_in_question": 2,
        "question_id": 2,
        "is_deleted": False,
    },
]
